trigger: 
- feature/*
- main

pool: Default

variables:
  workDir: '$(System.DefaultWorkingDirectory)/environments/dev'

stages:
- stage: Build
  displayName: Build
  jobs:       
  - job: TerraformInitPlan
    displayName: Terraform Init and Plan Job
    steps: 
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: $(workDir)
        backendServiceArm: 'GravtiasServiceConnection'
        backendAzureRmStorageAccountName: 'infrastorage4480143'
        backendAzureRmContainerName: 'infracontainer'
        backendAzureRmKey: 'gravitas.tfstate'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: $(workDir)
        environmentServiceNameAzureRM: 'GravtiasServiceConnection'

- stage: Scanning
  displayName: Scanning
  jobs: 
  - job: TFSecScanningJob
    displayName: TFSEC Scanning Job
    pool: Default
    steps:
    - task: tfsec@1
      inputs:
        version: 'v1.26.0'
        dir: $(workDir)

  - job: TfLintScanningJob
    displayName: TFLINT Scanning Job
    pool: Default
    steps:
    - task: CmdLine@2
      inputs:
        script: 'echo Hello world'

- stage: Deploy
  displayName: Deploy
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
  jobs: 
  - job: ManualValidation
    displayName: Manual Validation kardo Please
    pool: server
    steps:
    - task: ManualValidation@1
      inputs:
        notifyUsers: 'priyanshu10122@gmail.com'
        approvers: 'priyanshu10122@gmail.com'
        instructions: 'To check the plan first'

  - job: TerraformApply
    displayName: Terraform Apply Job
    dependsOn: ManualValidation
    pool: Default
    steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: $(workDir)
        backendServiceArm: 'GravtiasServiceConnection'
        backendAzureRmStorageAccountName: 'infrastorage4480143'
        backendAzureRmContainerName: 'infracontainer'
        backendAzureRmKey: 'gravitas.tfstate'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: $(workDir)
        environmentServiceNameAzureRM: 'GravtiasServiceConnection'