trigger: 
- feature/dev-branch
pool:
  name: Gravitas01

# Stages -> Jobs -> Steps ->Task
# Stages
#  Jobs
#   Steps
#    Tasks

stages:
- stage: Terraform
  displayName: Terraform Stage
  jobs:
  - job: TerraformJob
    displayName: Terraform Workflow
    steps:

    #1 Install Terraform
    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: '1.10.5'

    #2 Terraform init
    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
        backendServiceArm: 'GravtiasServiceConnection'
        backendAzureRmResourceGroupName: 'dev-aks-rg'
        backendAzureRmStorageAccountName: 'infrastorage4480143'
        backendAzureRmContainerName: 'infracontainer'
        backendAzureRmKey: 'gravitas.tfstate'

    #3 Terraform fmt
    - task: TerraformTask@5
      displayName: Terraform Fmt
      inputs:
        provider: 'azurerm'
        command: 'custom'
        customCommand: 'fmt'
        workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'

    #4 Terraform validate
    - task: TerraformTask@5
      displayName: Terraform Validate
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'

    #5 Terraform plan
    - task: TerraformTask@5
      displayName: Terraform Plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
        environmentServiceNameAzureRM: 'GravtiasServiceConnection'